services:
  backend:
    build:
      context: ./apps/backend
      target: development
    ports:
      - "3001:3001"
    env_file:
      - ./apps/backend/.env
    environment:
      NODE_ENV: development
    volumes:
      - ./apps/backend:/app
      - /app/node_modules
    depends_on:
      - cms
  frontend:
    build:
      context: ./apps/frontend
      target: development
    ports:
      - "3000:3000"
    env_file:
      - ./apps/frontend/.env.local
    environment:
      NEXT_PUBLIC_BACKEND_URL: http://localhost:3001
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
  cms:
    build:
      context: ./apps/cms
      target: development
    ports:
      - "1337:1337"
    env_file:
      - ./apps/cms/.env
    environment:
      NODE_ENV: development
    volumes:
      - ./apps/cms:/app
      - /app/.tmp
    tty: true
    stdin_open: true
